// <auto-generated />
using System;
using CloudContactManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace CloudContactManager.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
		protected override void BuildModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "8.0.0");

			// Subscription plans
			modelBuilder.Entity("CloudContactManager.Models.SubscriptionPlan", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd();

					b.Property<int>("MaxCustomers");

					b.Property<string>("PlanName")
						.IsRequired()
						.HasMaxLength(100);

					b.Property<decimal>("Price");

					b.HasKey("Id");

					b.ToTable("SubscriptionPlans");
				});

			// Users (tenants)
			modelBuilder.Entity("CloudContactManager.Models.User", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd();

					b.Property<string>("CompanyName")
						.HasMaxLength(200);

					b.Property<DateTime>("CreatedAt");

					b.Property<string>("Email")
						.IsRequired();

					b.Property<int?>("PlanId");

					b.Property<string>("PasswordHash")
						.IsRequired();

					b.Property<string>("Username")
						.IsRequired()
						.HasMaxLength(50);

					b.HasKey("Id");

					b.HasIndex("PlanId");

					b.HasIndex("Username")
						.IsUnique();

					b.ToTable("Users");
				});

			// Customers
			modelBuilder.Entity("CloudContactManager.Models.Customer", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd();

					b.Property<string>("Address");

					b.Property<DateTime>("CreatedAt");

					b.Property<string>("EmailAddress")
						.IsRequired();

					b.Property<string>("FullName")
						.IsRequired()
						.HasMaxLength(100);

					b.Property<string>("PhoneNumber")
						.IsRequired();

					b.Property<int>("UserId");

					b.HasKey("Id");

					b.HasIndex("UserId");

					b.ToTable("Customers");
				});

			// Campaigns
			modelBuilder.Entity("CloudContactManager.Models.Campaign", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd();

					b.Property<string>("CommunicationType")
						.IsRequired();

					b.Property<string>("MessageContent")
						.IsRequired();

					b.Property<DateTime>("SentAt");

					b.Property<int>("UserId");

					b.HasKey("Id");

					b.HasIndex("UserId");

					b.ToTable("Campaigns");
				});

			// Communication logs
			modelBuilder.Entity("CloudContactManager.Models.CommunicationLog", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd();

					b.Property<int>("CampaignId");

					b.Property<int>("CustomerId");

					b.Property<string>("DeliveryStatus")
						.IsRequired();

					b.Property<string>("ErrorMessage");

					b.Property<string>("ExternalId");

					b.HasKey("Id");

					b.HasIndex("CampaignId");

					b.HasIndex("CustomerId");

					b.ToTable("CommunicationLogs");
				});

			// Relationships
			modelBuilder.Entity("CloudContactManager.Models.User", b =>
				{
					b.HasOne("CloudContactManager.Models.SubscriptionPlan", "Plan")
						.WithMany("Tenants")
						.HasForeignKey("PlanId")
						.OnDelete(DeleteBehavior.Restrict);

					b.Navigation("Plan");
				});

			modelBuilder.Entity("CloudContactManager.Models.Customer", b =>
				{
					b.HasOne("CloudContactManager.Models.User", "User")
						.WithMany("Customers")
						.HasForeignKey("UserId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.Navigation("User");
				});

			modelBuilder.Entity("CloudContactManager.Models.Campaign", b =>
				{
					b.HasOne("CloudContactManager.Models.User", "User")
						.WithMany()
						.HasForeignKey("UserId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.Navigation("User");
				});

			modelBuilder.Entity("CloudContactManager.Models.CommunicationLog", b =>
				{
					b.HasOne("CloudContactManager.Models.Campaign", "Campaign")
						.WithMany("CommunicationLogs")
						.HasForeignKey("CampaignId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.HasOne("CloudContactManager.Models.Customer", "Customer")
						.WithMany()
						.HasForeignKey("CustomerId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.Navigation("Campaign");

					b.Navigation("Customer");
				});

			modelBuilder.Entity("CloudContactManager.Models.SubscriptionPlan", b =>
				{
					b.Navigation("Tenants");
				});

			modelBuilder.Entity("CloudContactManager.Models.User", b =>
				{
					b.Navigation("Customers");
				});
#pragma warning restore 612, 618
		}
    }
}
